---
- hosts: all
  remote_user: AdminSYS
  tasks:
  - name: Print the ansible os famili value
    debug:
      msg: '{{ ansible_os_family }}'
  - name: Ensure the package is installed
    yum:
      name: httpd
      state: latest
    become: True
    when: ansible_os_family == 'RedHat'
  - name: Ensure the apache2 package is updated
    apt:
      name: apache2
      state: latest
    become: True
    when: ansible_os_family == 'Debian' 
