--- 
- hosts: all 
  become: true 
  tasks: 
  - name: Ensure AdminSYS user exists 
    user: 
      name: AdminSYS
      state: present 
      comment: AdminSYS 
  - name: Ensure ansible user accepts the SSH key 
    authorized_key: 
      user: AdminSYS
      key: "{{ lookup('file', '/home/AdminSYS/.ssh/id_rsa.pub') }}" 
      state: present 
  - name: Ensure the Adminsys user is sudoer with no password required 
    lineinfile: 
      dest: /etc/sudoers 
      state: present 
      regexp: '^AdminSYS ALL\=' 
      line: 'AdminSYS ALL=(ALL) NOPASSWD:ALL' 
      validate: 'visudo -cf %s'
